name: flexisaf_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip
  - jupyter
  - notebook
  - ipykernel

  # Data handling & visualization
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm

  # ML & DL
  - scikit-learn
  - xgboost
  - lightgbm
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow

  # AutoML
  - flaml
  - pip:
      - auto-sklearn

  # Explainability
  - shap
  - lime

  # Utilities
  - requests
  - joblib

  # For experiments (optional but useful)
  - optuna
  - statsmodels
  - openml
  - mlflow
  - dvc
